import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./ui/components/Footer";
import Header from "./ui/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LLt Store",
  description: "Generated by Salman",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={"flex h-screen flex-col bg-red overflow-y-auto"}
        style={{
          scrollbarWidth: 'none'
        }}
      >
        <div>
          <Header />
        </div>
        <div className="h-screen bg-red">
          {children}
        </div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
