// app/layout.tsx or layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./ui/components/Header";
import Footer from "./ui/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LLt Store",
  description: "Generated by Salman",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="flex min-h-screen flex-col text-gray-900">
        <header className="w-full fixed top-0 left-0 z-50 bg-white">
          <Header />
        </header>

]        <main className="flex-1 pt-[80px]">
          {children}
        </main>

        <footer className="bg-black text-white">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
